BetterThanTomorrow/calva

- package.json
Hi @PEZ,
Not sure if it's okay to change a command's category to Calva - might confuse users? - but I did it to all of them. Also did some minor changes to commands description.
I just tried Calva with Shadow CLJS and it was easy to get it working, I'm very happy to see this! I've been teaching ClojureScript to new programmers and the editor integration has been a little bit of an issue. I use Cursive, but IDEs scare them off (I don't really understand it, it seems to be something psychological, not technical), and Emacs is even scarier and I'm not good at it to teach either. VSCode in the other hand is very popular and it's a very nice editor, so when they see that they can use VSCode for ClojureScript it's a thing less to learn (worry) and they feel more comfortable. 
I'm sure that the …
> The little details - Commands' category and description

- package.json
- src/main/calva/repl/middleware/lint.js
- src/main/calva/state.js
Hi, thanks for making this extension!
Currently I'm working with Visual Studio Code using the Windows Subsystem for Linux (WSL) for the integrated terminal while having the editor installed on Windows.
Since I installed Joker on the WSL (Ubuntu 16.04), Visual Studio Code wasn't able to find the executable of the linter through its path.
To fix this, I decided to add two new configuration options:
```json
"calva.jokerPath": {
"type": "string",
"default": "joker",
"description": "Sets the path in which the Joker executable can be found"
},
"calva.useJokerOnWSL": {
"type": "boolean",
"default": false,
"description": "Specifies if Joker will run through WSL"
}
```
I decided to add the `jokerPath` option in case the Joker executable is installed somewhere not included in the path environment …
> Add support for Joker on WSL

- calva/terminal.ts
When you pass keep focus true to terminal.show() it makes the editor keep the focus. There were many code paths where false was being passed
I removed the params from the outer methods as i couldn't think of a reason that we would want the terminal to take focus and it simplifies things a bit. If theres something im not considering (highly likely) let me know and ill re-add them
> prevent terminal from taking focus, cleaned up unnecessary params

- calva/repl/middleware/select.ts
I noticed a problem with selectCurrentForm.  It always failed on my setup, both Windows 10 and macOS, code version 1.26.1 and Calva version 1.3.36.
I tracked the problem to a type mismatch in select.ts:selectCurrentForm when assigning to editor.selection.  getFormSelection returns a vscode.Range type but editor.selection is vscode.Selection type.
I fixed by type annotating getFormSelection and then using the returned vscode.Range to construct a vscode.Selection and then assign to editor.selection.
I posted the differences in the Slack channel as well.
Let me know what you think.
Thank you,
Martin
> Bug in selectCurrentForm.  Type mismatch in editor.selection assignment.

- calva/utilities.ts
Hi team, thank you for this! I tried Cursive/Light Table/Emacs for Clojure dev, but settled on Calva + vscode.
I ran into an issue in using the `"calva.syncReplNamespaceToCurrentFile": true` configuration: the extension was not detecting the namespace in my `.clj` files correctly. This was because my namespace declarations were prefixed with some comments. For example:
This worked: if a file starts with any whitespace, followed by namespace declaration
```
(ns advent.2017.day20
(:require [clojure.string :as str]))
```
This did not work: file starts with a comment, followed by namespace declaration.
```
; http://adventofcode.com/2018/day/20
(ns advent.2017.day20
(:require [clojure.string :as str]))
```
This PR updates the namespace check to ignore comments and fix this issue. To summarize …
> Update namespace regex check to support comments

- calva/terminal.ts
A bug introduced by https://github.com/BetterThanTomorrow/calva/commit/6b587bb8992b14c55b66e6e9344cdb33eedcf812#diff-8df9e3e120042e77ce02d69fc87fbdecL127 means that `evaluateCurrentFormInREPLTerminal` evaluates the toplevel form, not the current one.
> Fix evaluateCurrentFormInREPLTerminal to not use toplevel form

- calva/connector.ts
Instead of assuming that everybody wants Figwheel and showing
error messages if figwheel is not started, we inform them about how
to get Figwheel working with Calva.
> Make figwheel a bit more optional for people not using it

- calva/repl/middleware/testRunner.ts
This was breaking the case when running tests in a test namespace. And also made the test runner miss when the namespace contained tests w/o being named something ending in `-test`.
> Stop always adding -test to the ns when running tests

- calva/repl/middleware/evaluate.ts
This PR improves "evaluate current file" productivity in two ways:
1. It shows the output.
2. It expands a short location of error into a long one that VSCode can convert to a link, so it is now:
```
Evaluating file: /Users/user/src/project/file.clj
Syntax error compiling at (/Users/user/src/project/file.clj:49:1).
```
> Show full error line in output

- calva/evaluate.ts
- calva/extension.ts
- calva/providers/annotations.ts
- package.json
Add an extra command to the extension that allows evaluating a form and display its result as a comment instead a decoration.
> Add evaluate as comment

- .gitignore
- .vscode/tasks.json
- package.json
- tsconfig.json
In this PR a did a few changes to the build process that hopefully will help in uncovering lingering problems in the code base:
- Make TS compilation faster by enabling --incremental
- Break TS compile task into two that run independently inside vscode: tsc and webpack
- Add problem matcher in the tsc task to enable global error visibility in vscode
- Declare these tasks as background tasks so they play nicely with vscode
> Improve build tasks

- calva/utilities.ts
There was a problem on windows with wrong project-root path.
uri.path was used that produced on windows a path with /c:/... 
The uri.fsPath produces the right path that works for all systems.
> Fixing not finding project.clj etc. on windows

- html/_theme-dark.scss
- html/_theme-light.scss
- html/styles.scss
When matched the brackets and parentheses where jumping, now the don't. Also added some styling, so it is clear when standing on matching brackets, parentheses etc.
> Added some color and fixed jumping brackets 

- package.json
I noticed a typo in a command description, and some inconsistent name casing. Thanks for making this extension 👏
> Fix typo in command description

- calva/calva-fmt/atom-language-clojure/grammars/clojure.cson
- calva/calva-fmt/atom-language-clojure/spec/clojure-spec.coffee
- clojure.tmLanguage.json
Explanation: the inner `string` and `regex` already consume the close
pattern, so it has to be matched with look behind on the `ignore-string`
and `ignore-regex`.
> Fixes ignored strings and regex

- calva/nrepl/jack-in.ts
With the latest version, the `jack-in` command tries the execute the below command 
```batch
> lein update-in :dependencies conj '[nrepl"0.6.0"]' -- update-in :plugins conj '[cider/cider-nrepl"0.21.1"]' -- update-in '[:repl-options :nrepl-middleware]' conj ["cider.nrepl/cider-middleware"] -- repl :headless
```
It results in below error.
```batch
zsh: no matches found: [cider.nrepl/cider-middleware]
```
If I ran the same command after wrapping ` ["cider.nrepl/cider-middleware"]` with a single quote it works as expected.
```batch
> lein update-in :dependencies conj '[nrepl"0.6.0"]' -- update-in :plugins conj '[cider/cider-nrepl"0.21.1"]' -- update-in '[:repl-options :nrepl-middleware]' conj '["cider.nrepl/cider-middleware"]' -- repl :headless
nREPL server started on port 62505 on host …
```
> [Bug Fix] lein jack-in command

- calva/repl-window.ts
This reverts part of the changes, introduced by #316. The point of the current change is to allow closing the REPL window without disconnecting the repl session.
@PEZ @cfehse
> Revert disconnecting and jacking out on closing of REPL window, resolves #326

- CHANGELOG.md
- calva/evaluate.ts
- calva/providers/annotations.ts
This pull request:
Fixes #104, and addresses #79.
- Inline result annotation now have a hover showing the full results.
- The hover has a `Copy` link, that copies the results to the clipboard.
- The inline displayed result takes up less width.
I have:
Ping: @kstehn
> Add a hover to results annotation w/ full results

- CHANGELOG.md
- calva/repl-window.ts
- html/images/empty.svg
- html/index.html
This pull request:
Fixes #341 .
- Added content security policy to `html/index.html `.
- Changed handling of image URL retrieval in `calva/repl-window.ts`. 
- Added an empty SVG image in `html/images`.
I have:
Ping: @pez, @kstehn
> Add content security policy to webview and remove image load error

- CHANGELOG.md
- calva/repl-window.ts
If an evaluation changes the namespace the change is populated back to the REPL window.
This pull request:
Fixes #280.
- `CANGELOG.md` as requested
- `calva/repl-window.ts` `REPLWindow.replEval()` method to populate a namespace change from the evaluation back to the repl window.
- 
(If you have considered alternative ways to introduce the change, replace this paragrah with a brief reasoning about why you made the choices you did. Otherwise just remove this paragraph.)
I have:
Ping: @pez, @kstehn
> Make REPL prompt reflect current NS reliably

- .vscode/launch.json
- .vscode/tasks.json
- package-lock.json
- package.json
- webpack.config.js
This pull request:
Fixes #346
Tested on following platform(s):
`webpack.config.js`
- Added comments to make the configuration more explainable. 
- Replaced all relative path values with resolved full qualified ones.
- The selection which packages to create is changed to evaluate the webpack `--mode`parameter.
`package.json` / `.vscode/tasks.json` / `.vscode/launch.json`
- Only one build task. This is simpler and  no order of execution required.
- Using the `concurrently` module for the `watch` script allows to see the output from both watchers (`webpack` and `tsc`).
- Removed the environment `IS_DEV_BUILD` because the the webpack `--mode`parameter is now used instead (see `webpack.config.js`).
- The build is now able to build from a clean `git clone` …
> [Fix] Simplify build system

- CHANGELOG.md
- README.md
- calva/evaluate.ts
- calva/extension.ts
- package.json
Resolves #349.
- Adds a command for evaluating the top level form, appending the result as a comment
- See #349 for rationale
I have:
Ping: @cfehse, @kstehn
> Add command evaluating top level to comment

- CHANGELOG.md
- calva/extension.ts
- package.json
Fixes #358.
- When "Pretty Print" setting is changed in settings (checked/unchecked) the "pprint" button in the status bar updates immediately
I have:
- [x ] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [x ] Made sure I am directing this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [x ] Made sure I am changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
- [x ] Referenced the issue I am fixing/addressing _in a commit message for the pull request_.
- [x ] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)
- [x ] …
> Update status bar when configuration changed

- src/nrepl/jack-in.ts
- Fixes a typo in the `calva.disconnect` command.
I have:
Ping: @pez, @kstehn
> Fix typo in jack-in command

- README.md
The link to About-Calva-Jack-in should be (I believe!) to Connect-Calva-to-Your-Project
Fixes #.
- 
- 
- 
I have:
Ping: @pez, @kstehn, @cfehse
> Fix broken link to Wiki

- src/nrepl/index.ts
- src/repl-window.ts
Fixes #371
- Add function for getting current REPL window without opening it
- Using this to stop opening the window in the default message handler
I have:
Ping: @kstehn, @cfehse
> Stop opening REPL window on async output

- CHANGELOG.md
- src/calva-fmt/src/config.ts
- src/calva-fmt/src/extension.ts
Don't remove default indentation when formatAsYouType is off. (Calva does this when it is responsible for auto indentation in order to get the cursor to end up at the beginning of the line outside top-level forms.)
Fix #253
I've added a config listener that toggles the `onEnterRule` off when `calva.fmt.formatAsYouType` is disabled.
I have:
- x ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.
Ping: @kstehn, @cfehse
> No onEnterRule when Calva is not auto-indenting

- CHANGELOG.md
- src/select.ts
Fixes #374.
- `select.ts` function `_adjustRangeIgnoringComment()` changed regex for `postMatch` to find the last ` )`.
I have:
Ping: @pez, @kstehn, @cfehse
> Fix issue 374

- CHANGELOG.md
- package-lock.json
- package.json
- src/calva-fmt/src/docmirror/index.ts
- src/repl-window.ts
Fixes #391.
-  Updated `package.json` to use `@types/vscode` package in the same version a specified in the `engines` definition.
-  Removed type/compiler error which was caused by this update in `docmirror/index.ts`
-  Change URI generation in `repl-windows.ts` to use the `webview.asWebviewUri()` method.
I have:
Ping: @pez, @kstehn, @cfehse
> Fix issue 391

- CHANGELOG.md
- src/calva-fmt/src/extension.ts
- Fix find definition / hover for derefed symbol
- Fix find definition / hover for var quoted symbol
Fixes #106 
I have:
NOTE: I thought I saw an issue in the past about the issue with hover definition for symbols (like `'some-thing`), but I can't find it now. Also, do you think changing the wordPattern as such would negatively affect any other part of the extension?
> Fix - find definition for derefed value

- CHANGELOG.md
- src/webview/clojure-lexer.ts
This fixes issue #463 by including an optional `#` in front of a string literal which gets regex literals tokenised as strings.
I think that regex literals should probably be tokenised to regex literals instead, but that is a bigger change, and this tiny change seems to fix the actual issue for the user. I propose we put the proper fix on the todo-list.
Please look at the tiny code change and help think about potential side effects, and help test that the change doesn't break things.
I have:
> Fix: Lexing regex literal tokenisation

- CHANGELOG.md
- src/testRunner.ts
- Add test message to the test runner output
- Reformat error and failure test runner output
Closes #425 
```clj
(deftest fail-test
(testing "The test context"
(is (= 1 2) "Math is hard")
(is (= 1 3))))
```
```
FAIL in my-project.upload-helpers-test/fail-test (upload_helpers_test.clj:10):
The test context: Math is hard
expected: 1
actual: (2)
FAIL in my-project.upload-helpers-test/fail-test (upload_helpers_test.clj:11):
The test context
expected: 1
actual: (3)
```
```clj
(deftest fail-test-2
(is (= 1 2)))
```
```
FAIL in my-project.upload-helpers-test/fail-test-2 (upload_helpers_test.clj:14):
expected: 1
actual: (2)
```
```clj
(deftest error-test
(testing "The test context"
(is (= (/ 1 0) 1) "The test message")))
```
```
ERROR in my-project.upload-helpers-test/error-test (line 19):
The …
```
> Add test message to test runner

- CHANGELOG.md
- src/webview/clojure-lexer.ts
- In the REPL window, syntax highlighting, and Paredit commands regarding something like ``'`'`'@'(foo)``, now considers that as one token, instead of three, as it used to.
- This also fixes how the signature help matches active parameter for an argument like this.
- _NB: It does not fix Paredit commands in the editor, because they do not use our own Paredit yet._
This is fixed such that the tokenizer now considers all combinations of the characters ``'.`~@``, in any order and with any (one-line) whitespace between as one token, together with the list, symbol, or literal they prepend. I am using this regex: ``/(['`~@][\s\r\n]*)*/``, prepended in front of the token regexes for lists, literals, etc.
It also involves a different check for valid matching pairs. Where we used to have a …
> [WIP] Lex quoted stuff

- src/extension-test/unit/cursor-doc/mock.ts
- src/extension-test/unit/cursor-doc/paredit-test.ts
I have added two unit tests for `paredit.ts`:
* `selectRangeFromSelectionEnd`– Fails 😭 , which is consistent with issue #498 
* `selectRangeFromSelectionStart` – Succeeds 🎉 
Looks like so when Test Explorer reports the results when I save the test file:
Posting this as a PR, because I want feedback on the way I have factored the test before we go about adding more tests in the same MO. 
I have:
> Add first two paredit tests, one failing

- CHANGELOG.md
- package.json
- src/providers/infoparser.ts
- src/state.ts
- Format hover docstrings with `MarkdownString`
- Format completion docstring
- Add docstring to signature information
Currently multi-line docstrings are very hard to read because VS Code doesn't respect newlines.  I think this is behavior that should be fixed with VS Code, but this PR fixes this by using `MarkdownStrings` to format the hover text.
The fix was possible by formatting the docstring as a codeblock, which preserves most of the docstring formatting.  One thing to note is that this does seem to make my font a little bigger in the docstring portion, but I think this is fine since it is much more important to properly format the docstring.
I tested out adding the docstring to the signature since I think this is when the docstring is most useful, I'm not sure if others have a …
> Use MarkdownString to format docstring

- CHANGELOG.md
- docs/readthedocs/source/commands-top10.md
- docs/readthedocs/source/try-first.md
Keybinding for Windows was not correct. Added a clarifier to the documentation to call out the difference.
Fixes #533
I have:
> Fix missing Windows keybinding in documentation.

- CHANGELOG.md
- clojure.tmLanguage.json
- docs/grammar/things-to-consider.md
- docs/readthedocs/source/customizing.md
- package-lock.json
- package.json
- src/calva-fmt/atom-language-clojure/grammars/clojure.cson
- src/calva-fmt/atom-language-clojure/spec/clojure-spec.coffee
- src/calva-fmt/clojure.tmLanguage.json
- src/cursor-doc/clojure-lexer.ts
- src/cursor-doc/token-cursor.ts
- src/extension-test/unit/cursor-doc/clojure-lexer-test.ts
- test-data/test2.clj
- The lexer now produces one token for tokens that are preceded by a reader tag (like `#uuid`), for when the tag is on the same line.
- If the tag is on a separate line we produce a `reader` token, and the token cursor is made aware of this when doing `backward-sexp`.
This PR also introduces [fast-check](https://github.com/dubzzz/fast-check) for testing the scanner
Used for
Should probably be used for 
And more.
Also we should use it for
I have:
> Make token cursor handle reader tags

- CHANGELOG.md
- clojure.tmLanguage.json
- src/calva-fmt/atom-language-clojure/grammars/clojure.cson
- src/calva-fmt/atom-language-clojure/spec/clojure-spec.coffee
`nil` followed by a comma was not being handled approriately for highlighting. #577
`true` and `false` had some issues too. #578
Handling of `nil`, `true`, and `false` should be improved.
The test for `nil` and that of booleans was also added to.
I have:
Fixes #577 #578
> Tweak handling of nil, true, and false in grammar

- CHANGELOG.md
- src/cursor-doc/paredit.ts
- src/cursor-doc/token-cursor.ts
- src/extension-test/unit/cursor-doc/clojure-lexer-test.ts
- src/extension-test/unit/cursor-doc/paredit-test.ts
- src/extension-test/unit/cursor-doc/token-cursor-test.ts
- src/highlight/src/extension.ts
- test-data/test2.clj
Fixes #581 
- The token cursor has two new methods for moving forward and backwards through reader tokens, even when they are stacked.
- These are then used by some the primitive token cursor movement operations, forward/backward sexpr and up/down list.
- They are also used from some Paredit operations, because they had to.
- They are also used from Calva Highlight to get the rainbows right.
Here's a demo:
A summary of what is going on in the GIF:
1. I am painting the reader tags with the same rainbow color as any list they are tagging. 
2. The session starts with expanding the selection a few times from the `nil` form.
3. Then I move past the `#foo-0` tagged list and back again.
4. Then I move down into to the` #foo-0` tagged list.
5. I drag the `1` forward through all its siblings in …
> A reader aware token cursor

- CHANGELOG.md
- src/cursor-doc/clojure-lexer.ts
- src/cursor-doc/paredit.ts
- src/cursor-doc/token-cursor.ts
- src/extension-test/unit/cursor-doc/clojure-lexer-test.ts
- src/extension-test/unit/cursor-doc/paredit-test.ts
- src/extension-test/unit/cursor-doc/token-cursor-test.ts
Right now strings are not closing when a double quote is entered at the end of the string. And this also is sometimes happening for lists/vectors/etcetera. Both problems [are mentioned on ClojueVerse](https://clojureverse.org/t/it-is-super-easy-to-hack-on-calva-why-dont-you-try-it-out/4953/3?u=pez). It turns out that the functionality for determining if we are in a string is quite broken, and the methods for closing lists too. This PR fixes both, and in addition to that improves the handling of quoted quotes inside strings.
Fixes #587
> REPL window prompt string closing

- CHANGELOG.md
- package-lock.json
- package.json
- src/nrepl/connectSequence.ts
- src/nrepl/jack-in.ts
- src/nrepl/project-types.ts
- src/state.ts
A `generic` project type is added. This project type is not selectable at jack-in, but always on connect. Running the connect command In a project that has no Calva-known project files will bring up the connect prompt asking for nREPL url (pre-filled with port, if there is an `.nrepl-port` file. If there are such files, the project type `Generic` is added to the list of selectable project types.
Currently if there are custom sequences configured and one of them is of type `generic`, it will show up for Jack-in scenarios, but will not result in a jack-in starting. (A message in **Calva says**, informs about it.)
Fixes #595 
I have:
> [WIP] Add support for connecting to generic project types

- CHANGELOG.md
- src/connector.ts
- src/evaluate.ts
- src/nrepl/index.ts
- src/nrepl/jack-in.ts
- src/repl-window.ts
- src/utilities.ts
- All uses of the nrepl client `eval()` op now are required to pass `ns`.
- Many uses send along the current client `ns`, as that makes more sense than sending `user`.
I have:
> Always send along `ns` w/ nrepl eval

- CHANGELOG.md
- package.json
- Removes Calva-specific commands from editor context menus when not in a _clojure_ file (per `editorLangId`
- Disentangles filtering on the context menu (via `when`) from enablement when present (via `enablement`)
Fixes #615 
I have:
> Filter Calva commands from editor context menu when not in Clojure files

- CHANGELOG.md
- src/cljs-lib/src/calva/fmt/formatter.cljs
- src/cljs-lib/test/calva/fmt/formatter_test.cljs
When formatting, Calva goes to considerable length to keep the cursor at the right place after reformatting. Currently we use a quite hackish regexp match of the tail of the document to achieve this. In rare occasions this regex match runs amok and never finishes. Causing Calva to stop working entirely. These rare occasions get more common when the whole document is formatted. But it was just a mistake that the position restore is applied in these cases, because VS Code takes excellent care of that. So this PR fixes that mistake. Which should make it much less common that users run into this problem.
Fixes #651 (Well, makes it less likely to happen at least)
I have:
> Remove unnecessary cursor position restore, that sometimes causes Calva to stop functioning

- CHANGELOG.md
- src/cursor-doc/clojure-lexer.ts
- src/extension-test/unit/cursor-doc/clojure-lexer-test.ts
- Fix tokenizing of open parens/brackets/braces when var quote precedes it
Fixes #663 
I have:
> Fix higlight of var quote before open token

- CHANGELOG.md
- package-lock.json
- src/nrepl/connectSequence.ts
- src/nrepl/project-types.ts
- Remove piggieback middleware from shadow-cljs sequences
- Always combine custom connect sequences with default connect sequences
Fixes #675
Fixes #685 
Note about #685, I think it makes sense to restrict user-defined custom connect sequences for shadow-cljs to have a string for connect code. The internal/default connection uses an object to handle whether the user chooses to connect to a build or start a browser/node repl. If the user defined a custom connect sequence then they should supply the connect code to start the build/repl of their choosing. 
I have:
> Fix Clojure CLI + shadow-cljs jack-in error and combine custom and default connect sequences

- src/evaluate.ts
- src/extension.ts
Adds support for a command to evaluate arbitrary code on the current session. It is meant to be used when scripting vscode, like writing other extensions or using existing extensions like [macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros). I'm using it like such:
```json
"macros": {
"cljMountRefresh": [
"workbench.action.files.saveAll",
{
"args": "(mount.lite/stop)",
"command": "calva.evaluateUser"
},
"calva.refresh",
{
"args": "(mount.lite/start)",
"command": "calva.evaluateUser"
}
]
},
```
Fixes #690.
I have:
> add evaluateUser command for evaling arbitary code

- CHANGELOG.md
- src/evaluate.ts
While we figure out how to signal this in a less annoying way...
Fixes #717
I have:
> Stop popping up output window when load file has errors

- CHANGELOG.md
- src/calva-fmt/src/format.ts
- Our range format provider now checks if the range starts inside a string, and if so skips creating an edit
Fixes #720
I have:
> Don't format range if inside string

- CHANGELOG.md
- src/debugger/decorations.ts
- src/debugger/util.ts
- src/evaluate.ts
- src/extension-test/unit/debugger/util-test.ts
- A call to `in-ns` was previously a separate eval before evaluating the user's code. This change adds the call inside a `do` followed by the user's code.
- Update the debugger breakpoint finding logic and tests to account for the additional code, essentially ignoring it when finding breakpoints, since the added code is not actually in the file.
- Add comments explaining these changes where necessary to help prevent regressions, though the unit tests for the debugger should fail if a change breaks the breakpoint finding logic in the future.
Fixes #724 
I have:
> Fix usage of dynamic vars *1, *2, and *3 for accessing recent results

- CHANGELOG.md
- src/calva-fmt/src/format.ts
- Fix format on paste (correct typo where range.start was used when it should have been range.end)
Fixes #730 
I have:
> Fix format on paste

- CHANGELOG.md
- src/evaluate.ts
- src/nrepl/index.ts
Also:
- Do not print stdout as being stderr
(venatius/ultra must handle its own bugs)
- Print out-of-band stdout to output window (not Calva says)
Fixes #738
I have:
> Stop trying to print stacktrace when there is none

- CHANGELOG.md
- package-lock.json
- package.json
- as per [Calva's ESC keybinding overrides VS Code's (useful) default](https://github.com/BetterThanTomorrow/calva/issues/740)
- just a quick change to keybinds in package.json. I don't think there's another way to do it
Fixes #740 https://github.com/BetterThanTomorrow/calva/issues/740
I have:
- I *think* esc operates similarly everywhere from memory, but don't currently have a non-linux box to check on
> fix #740 - Stop overriding vs code's default esc  keybinding

- CHANGELOG.md
- src/calva-fmt/src/format.ts
- Disallow **top level** formatting in the output file (because it breaks the prompt).
- Do not perform **top level** formatting after paredit command, only when tab is pressed on an empty line. Fixes this:
Fixes #700 
I have:
> Fix top level formatting (#700)

- CHANGELOG.md
- src/calva-fmt/src/format.ts
- Check for formatRange before calling includes on it, to avoid an error
Fixes #753 
I have:
> Fix format error

- CHANGELOG.md
- src/evaluate.ts
- Show stacktraces in output window
Fixes #758
I have:
> Fix stacktraces not showing in output

- CHANGELOG.md
- src/providers/annotations.ts
We need to clean the decoration only if the event contains real changes.
Fixes #774 
I have:
> Fix inline evaluation result dissapears after a second (#774)

- CHANGELOG.md
- src/results-output/results-doc.ts
- src/state.ts
- src/utilities.ts
- Make getDocument check for languageId and only return a document if the languageId is not `Log`. This prevents a Log document from the bottom output pane being returned as a document.
Fixes #771 
I have:
> Fix getDocument to not return a Log document

- CHANGELOG.md
- src/cljs-lib/src/calva/parse.cljs
During parsing of project.clj files, if there were any `evals` it would throw an exception and ultimately not allow the user to jack-in.
- The chosen solution is so replace `#=\(` with `nil #_(`
- Why `nil`? If an `eval` was used as a value in the map you would get an exception too. Covered by the test case added.
Example error with eval as map value:
```
Error: The map literal starting with :a contains 1 form(s). Map literals must contain an even number of forms.
```
Fixes #763 
I have:
> Fix: evals should be ignored during parsing

- CHANGELOG.md
- src/state.ts
- src/utilities.ts
- When finding test under cursor, checks that token starts with 'def' instead of checking that it equals `def`, `defn`, or `deftest`. This allows using custom test macros that begin with `def`.
Fixes #786 
I have:
> Check if token begins with 'def' when finding test

- CHANGELOG.md
- docs/site/finding-commands.md
- package.json
- src/config.ts
- src/extension.ts
- src/paredit/statusbar.ts
Closes #784
We introduce a `calva.keybindingsEnabled` config option and a
`calva.toggleKeybindingsEnabled` command which allows toggling
keybindings on and off. The keybindings are updated to only activate
when the `calva:keybindingsEnabled` context key is true, in addition to
the existing conditions on the keymap.
Also includes minor improvement to Paredit StatusBar code.
Tested in VSCode 1.48.1 on Arch Linux.
I have:
> Allow toggling keyboard shortcuts

- CHANGELOG.md
- docs/integration.md
- src/nrepl/project-types.ts
- Change nrepl version for jack-in to 0.8.2
Fixes #777 
I have:
> Update nrepl vesion for jack in to 0.8.2

- CHANGELOG.md
- src/liveShareSupport.ts
- src/nrepl/jack-in.ts
- Adds null checks around calls to live share library's `getApi` which returns null if the live share extension is not installed, or if there was some issue
Fixes #821 
I have:
> Fix broken jack-in

- CHANGELOG.md
- src/nrepl/project-types.ts
- src/state.ts
- Set project root directory uri in all cases when initializing project directory, so that jack-in works in multi-project workspaces
Fixes #821 
I have:
> Fix multi repo jack-in

- CHANGELOG.md
- src/state.ts
When initialising the project directory we used `vscode.Uri.parse(rootPath)` resulting in a broken the Uri object on Windows. It got `schema: c`, and some follow-up funniness.
We now use `vscode.Uri.file()` instead.
Fixes #827 #825
I have:
> Fix Windows jack-in regression

- CHANGELOG.md
- package-lock.json
- package.json
- src/state.ts
- `PROJECT_DIR_URI_KEY` (aka `getProjectRootUri()`) is determined using a new algorithm. The old algorithm only worked locally, not for remote use cases e.g. live share.
Note: this affects all platforms. I could only test it with macOS. I also did a quick check with a colleague who is on Windows. Using a multi-project folder it worked correctly in both directions.
Fixes #831
I have:
> Fix: Connect to REPL as live share guest in multi-project workspace

- docs/site/rebl.md
Removes the wrong space in the `nrepl.cmdline` from the `How to Use Calva and REBL Together` doc
The *How to Use Calva and REBL Together* doc page has a typo, some space characters in the `nrepl.cmdline` which makes the example alias to fail. This PR just removes that typo.
I have:
- [ x ] Read [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#before-sending-pull-requests).
- [ x ] Directed this pull request at the `dev` branch. (Or have specific reasons to target some other branch.)
- [ x ] Made sure I have changed the default PR base branch, so that it is not `master`. (Sorry for the nagging.)
> Fix REBL doc typo

- CHANGELOG.md
- src/state.ts
Fix jack-in prompt never appearing on Windows.
Doesn't seem to happen to users out there, but on my Windows machine jack-in doesn't work.
The fix is to wrap the `fs.stat()` call in a try/catch instead of using the return value. Quite strange, but it is how the [VS Code team is recommending it to be done](https://github.com/microsoft/vscode-extension-samples/blob/master/fsconsumer-sample/src/extension.ts). (And also, it does fix the problem.)
Fixes #885
I have:
- ~[ ] Added to or updated docs in this branch, if appropriate~
> 885 fstat await problem

- CHANGELOG.md
- src/debugger/calva-debug.ts
- src/extension-test/unit/util/string-test.ts
- src/testRunner.ts
- src/util/string.ts
- Use vscode.Uri to openTextDocument instead of a string path
Fixes #893 
I have:
> Fix step into local dep with debugger

- CHANGELOG.md
- src/lsp.ts
- src/providers/definition.ts
In the lsp `clientOptions` `middleware` we first check if cider-nrepl hands us any symbol definitions. If it does we return those, otherwise `clojure-lsp` gets a chance. This gives us a ”best of both worlds” behaviour. With tried and tested cider-nrepl definitions, and then local bindings and such from lsp (or only lsp stuff if no repl is started for the project).
It also works around a current issue we have with our lsp integration acting up on Windows.
Addresses #897
I have:
- ~[ ] If I am fixing the issue, I have used [GitHub's fixes/closes syntax](https://help.github.com/en/articles/closing-issues-using-keywords)~
- ~[ ] Created the issue I am fixing/addressing, if it was not present.~
- ~[ ] Added to or updated docs in this branch, if appropriate~
Before merging we (at least one of …
> Use nrepl definitions when available

- CHANGELOG.md
- src/lsp.ts
- Send a non-encoded document uri to clojure-lsp for the refactoring commands. Previously the `:` after the Windows drive letter was being encoded to `%3A` by the `TextDocument.uri.toString()` function, but clojure-lsp indexes the files without this encoding (like `c:\`).
I tested this in Windows and Linux
Fixes #911 
I have:
- ~[ ] If I am fixing just part of the issue, I have just referenced it w/o any of the "fixes” keywords.~
- ~[ ] Added to or updated docs in this branch, if appropriate~
> Fix lsp refactorings on windows

- CHANGELOG.md
- src/extension.ts
- src/lsp.ts
Reactivate nrepl definition provider
And then run it from the lsp provider as well to see if it would answer
If so lsp provider returns null
Fixes #915
I have:
> Wake up core navigation again

- src/utilities.ts
I tested this in Windows and Linux with and without a repl connection. It works even if the windows path contains `/` instead of `\` (no need to replace). The fix involves removing the extra `/`s in front of the drive letter for Windows, but leaving them for Unix based OS's.
> Fix getJarContents for windows

- CHANGELOG.md
- src/highlight/src/extension.ts
We were not allowing the `forwardSexpr` of the token cursor used for dimming ignores to skip past metadata.
Fixes #908
There are still issues with the stacking of ignores in the presence of metadata, but this at least takes care of the reported case.
I have:
> Make dimming of ignores skip meta and ignores
