BetterThanTomorrow/calva

src/statusbar.js
Minor changes to statusbar. See what you think @PEZ .
=> Status Bar

package.json, src/connector.js
Changed default command to start Figwheel REPL.
=> Start Figwheel REPL

calva/extension.ts, calva/repl/middleware/evaluate.ts, package.json
this feature was missing seemed like a no brainer
=> added top level pretty print command and shortcut

calva/extension.ts, calva/state.ts, package.json
added a simple implementation that mimics intellijs behavior, i think its convenient and beginner friendly so defaulted to on. let me know what you think
=> added option to sync repl namespace to current file

package.json
=> Fix spelling in package.json

calva/repl/middleware/evaluate.ts
=> Show stdout and stderr output when loading a file

calva/connector.ts
I work in an environment, where I have multiple clojure projects opened in the same workspace. This PR allows the extension to figure out correct nrepl port based on the active file.
=> Find parent .nrepl-port file

calva/connector.ts, calva/repl-window.ts
=> Fix race condition while initialising cljs repl

html/styles.scss
less blinking and skinnier caret in repl window
=> calmer caret in repl

README.md
I guess that's self-explanatory. :-)
=> Update CIDER link

README.md
Added a note for windows users to change shell from Powershell to Cmd
=> Added a note for windows users to change shell

calva/statusbar.ts, package.json
Add option to customize the statusbar color item.
This soves the issue #96 .
=> Made statusbar color configurable

calva/repl-window.ts, package.json
https://github.com/BetterThanTomorrow/calva/issues/229
=> Keep focus in editor window when eval current form in REPL window

.circleci/config.yml, .vscode/tasks.json, package.json
Add circleci build.
Automates the test running and also creates the vsix artifact.
=> Add circleci

CHANGELOG.md, calva/nrepl/jack-in.ts, package.json
Reverts BetterThanTomorrow/calva#318
=> Revert "Fix/figwheel main deps when no cljs 317"

.vscodeignore, assets/webview.html, calva/webview/index.ts, package-lock.json, package.json, webpack.config.js
One last thing - which was some kind of a "flaw" to me - about the build system I want to change is that the webview is not debugable either in vscode nor in the Webview Developer Tool from vscode.  This can relatively easy be a achieved by changing the property `devtool`  to `'eval-source-map'` in `webpack.config.js` for non production modes. Because of that the content security policy for the webview must now include `'unsafe-eval'` for the `script-src`. 
The other changes are more of a housekeeping kind. I removed the unused scripts in `package.json` to start the webview in the webpack dev server (these scripts did not work anyway for me- at least not in this configuration). I removed the then unused `calva/webview/index.ts` file as well.  I added `npx i` to the `prewatch` script. This …
=> Make webview debugable in vscode Webview Developer Tool

src/calva-fmt/README.md
Hi all, just a simple fix to correctly display GIF in `calva-fmt` readme :slightly_smiling_face: 
I have:
Ping: @pez, @kstehn, @cfehse
=> Fix GIF display in calva-fmt readme

CHANGELOG.md, package-lock.json, package.json, src/webview.ts
Fixes #257.
- Store the new namespace name in the `'set-in!'`handler.
- Removed runtime exceptions if the completions object is undefined in message.
- Removed unused code.
I have:
Ping: @pez, @kstehn
=> Fix issue 257

CHANGELOG.md, src/repl-window.ts
- In the REPL window connect handler check is the retrieved namespace is defined.
Fixes #115
I have:
=> Check if namespace is defined on REPL window connect.

CHANGELOG.md, src/nrepl/index.ts
- when nrepl returns a request for user-input, print a error msg to the user and set nrepl's stdin to an empty line
- more work is needed to support handling user-input, will look into it and hopefully submit another PR?
- in the meantime, this patch will stop Calva's REPL window from hanging
Fixes #377 
I have:
=> handle nrepl input request with error msg

docs/readthedocs/source/connect.md
- Add a mention of CIDER nREPL in the documentation section "Connect Calva to Your Project". I spent a good amount of time trying to figure out why most features in Calva did not work, so I thought I'd spare others from this by documenting it.
I have:
=> Add mention of CIDER nREPL in the documentation

CHANGELOG.md, src/evaluate.ts
- The promise returned by `evaluateSelection` was not handled correctly. Now possible errors from the promise are caught and logged.
Fixes #411 
I messed the previous PR/branch that was addressing this issue when I was merging changes from upstream. Now this branch should be fresh and up to date.
I have:
=> Handle floating promises

CHANGELOG.md, README.md, src/webview/lexer.ts
- Made the lexer in `webview/lexer.ts` more efficient. The output for the sample code in the issue will not be printed as quickly as in a console REPL but nearly.
Fixes #128 #228 
I have:
Ping @pez, @kstehn, @bpringe
=> Made lexer more efficient

CHANGELOG.md, package.json, src/connector.ts, src/repl-window.ts, src/state.ts
- Added option to select the initial view column for the REPL windows. The default is `Two` to preserve the current behavior.
- Added option to select if the REPL windows should be opened on connect. The default is `true`to preserve the current behavior.
Fixes #300
I have:
Ping @pez, @kstehn, @bpringe
=> Added initial view column option for REPL windows

src/webview/model.ts
- Corrected error where the wrong lines marked dirty in `changeRange()`.
I have:
Ping @pez, @kstehn, @bpringe
=> Correct error where wrong lines marked dirty in changeRange()

CHANGELOG.md, src/webview.ts, src/webview/paredit.ts, src/webview/readline.ts, src/webview/token-cursor.ts
1. The readline module matches the opening bracket for the token immediately preceding the cursor, if it is a closing bracket.
1.  REPL window Paredit Grow Selection selects form to grow consistent with 1.
Please try this out in the REPL window.
Behind the scenes I have introduced a **Move to Current Form** method on the Token Cursor. This will come in handy when we switch to this Paredit for the editor and want to have a consistent notion of what is the current form.
Fixes #472 
I have:
=> Match opening bracket when cursor is after closing

CHANGELOG.md, docs/readthedocs/source/paredit.md, src/cursor-doc/model.ts, src/cursor-doc/paredit.ts, src/doc-mirror/index.ts, src/extension-test/unit/cursor-doc/mock.ts, src/extension-test/unit/cursor-doc/paredit-test.ts, src/extension-test/unit/util/string-test.ts, src/paredit/extension.ts, src/webview/readline.ts, src/webview/repl-console.ts
WIP: I am fixing the issue and also adding some  unit tests for the Paredit grow and shrink selection stack.
Eventually #506 should be fixed. 😄 
I have:
=> Fixing #506 select back/fwd stack issue w/ selection can't grow

CHANGELOG.md, assets/styles/webview.scss, package-lock.json, src/webview.ts, src/webview/repl-console.ts
Evaluating something like this in the REPL window
```clojure
(str "foo " (deadline))
```
Worked quite strangely. Most often repeating the `stdin` input prompt, but also doing other things at times...
We were removing the div containing the input element for the `stdin` input from within the element event handler, and that didn't seem to work. (I am pretty sure it has worked before, but probably stopped working when the whole submit-line thing is wired up differently.)
We are now using a state variable to inform the Webview readline msg handler about the type of input. This state variable is set to `true` when the input element is created and to `false` in the Webview readline message handler, which also removed the input element.
Works in my testing, but would be great if @cfehse could …
=> Move user-input to msg handler, fixing `(read-line)` issue

src/webview.ts
For some users, the REPL Window is often not accepting keyboard commands, like cursoring, return and such. In this PR I am enabling those commands on a few more Webview events to try see if that helps Calva know when the commands should be dispatched to the  REPL Window.
When this worked it should fix #516
I have:
=> Fix REPL Window not accepting keys like cursor, return, etcetera

CHANGELOG.md, src/webview.ts
I had missed changing how the readline selection was fetched and updated in the autocompletion case.
Fixes #519
**NB**: I am very surprised that the TypeScript compiler let this through. It is probably some sloppy setting in our tsconfig.
TODO: Tighten up the tsconfig so that bugs that this do not build.
I have:
=> Stop using non-existing model selection accessors

CHANGELOG.md, src/cursor-doc/paredit.ts
Strict mode backspace and delete now checks for bracket matching before avoiding to delete brackets (instead of just refusing to delete brackets).
Fixes #501
I have:
=> Paredit deleting checks for balanced bracket

docs/readthedocs/source/vim.md
Clarify Vim escaping to command mode. 
Ref: https://vim.fandom.com/wiki/Avoid_the_escape_key#Avoiding_the_Esc_key
I have:
=> docs(vim): note native vim escape command

CHANGELOG.md, package-lock.json, src/repl-window.ts, src/utilities.ts, src/webview/repl-console.ts
- Added debounce to repl window functions that are mapped to alt key (whether in single- or multi-line mode). This fixes the issue on Linux where commands called with alt+up or alt+down are somehow called twice in succession.
Fixes #491 
I have:
This could use some testing before merging, but so far it works smoothly on my Ubuntu machine.
=> Fix/repl window history for Linux

CHANGELOG.md, package.json, src/nrepl/index.ts, src/nrepl/project-types.ts, src/state.ts
Fixes #552
Latest cider-nrepl makes `suitable` JavaScript completion opt-in, which made these completions stop working with shadow-cljs. (Shadow brings in the nrepl dependencies itself, so that Calva can't really control the versions used.)
I have:
=> Add option for enabling suitable JS completions

CHANGELOG.md, docs/readthedocs/source/customizing.md, package.json
=> Auto parameter hints off by default

CHANGELOG.md, package.json, shadow-cljs.edn, src/calva-fmt/src/config.ts, src/calva-fmt/src/format.ts, src/cljs-lib/src/calva/fmt/formatter.cljs, src/cljs-lib/src/calva/fmt/util.cljs, src/cljs-lib/src/calva/parse.cljs, src/cljs-lib/test/calva/fmt/formatter_test.cljs, src/cursor-doc/indent.ts, src/files-cache.ts, src/state.ts
- new configration for cljfmt config file path `calva.fmt.configPath`
This is alternative approach to #544.
Example setting
```json
"calva.fmt.configPath": "./cljfmt.edn",
```
`./cljfmt.edn`
```edn
{:remove-consecutive-blank-lines? false
:indents ^:replace {#".*" [[:inner 0]]}}
```
```clojure
[1 2 3
4 5 6]
{:key-1 v1
:key-2 v2}
#{a b c
d e f}
(or (condition-a)
(condition-b))
(filter even?
(range 1 10))
(clojure.core/filter even?
(range 1 10))
(filter
even?
(range 1 10))
```
Fixes #80
I have:
=> Cljfmt configuration file

CHANGELOG.md, docs/readthedocs/source/connect-sequences.md, docs/readthedocs/source/customizing.md, docs/readthedocs/source/index.rst, docs/readthedocs/source/luminus.md, docs/readthedocs/source/rebl.md, docs/readthedocs/source/remote-development.md, docs/readthedocs/source/using-with.rst, docs/readthedocs/source/vim.md, docs/readthedocs/source/wsl.md, package.json, src/nrepl/connectSequence.ts, src/nrepl/project-types.ts
Addressing the issue about [bad Ux for lein-shadow projects](https://github.com/BetterThanTomorrow/calva/issues/585)
- A new connect sequence project type is added: `lein-shadow`
- The existing `lein` and `shadow-cljs` project types are refactored to avoid some of the duplication.
Tested on:
Fixes #585
I have:
=> Add lein-shadow jack-in/connect project type

docs/readthedocs/source/jack-in-guide.md
=> fix broken link for connect-sequences docs

docs/readthedocs/source/vim.md
Just found a small spelling mistake, hope i managed to follow all the guidelines
I have:
=> Fix small spelling error

CHANGELOG.md, README.md, assets/webview.html, src/extension.ts, src/greet.ts
- This PR only updates all readthedocs.io links to calva.io
Fixes #604 
I have:
=> Updating documentation links

CHANGELOG.md, package.json, src/highlight/src/extension.ts
Fixes #620
- Indent guidelines are painted are rendered with the same color as their corresponding bracket
- No guides are rendered where there is no corresponding bracket
- VS Code default guides are switched off for Clojure files
I have:
=> [WIP] Render rainbow indent guides

CHANGELOG.md, assets/styles/webview.scss
- background and foreground colors in suggestion popup in REPL window.
Fixes #623
I have:
=> Fix colors in suggestion popup (REPL window)

.vscode/launch.json, CHANGELOG.md, src/calva-fmt/src/config.ts, src/connector.ts, src/extension.ts, src/nrepl/project-types.ts, src/state.ts
Calva has some deep assumptions about all Clojure things being part of a project, and the projects being of certain types and having certain files and such. I think there is a huge chunk of work waiting there for us to deal with it. This PR fixes some key places in the code where the assumptions get in the way for getting Calva's help on a bare Clojure file. Especially relevant for *babashka*. 
While at it I also added some try/catch wrappings for places where the activation of Calva might otherwise just fail. Hoping it will produce more useful error reports than ”No Calva commands work, at all”.
Fixes #622
I have:
=> Handle bare files (non-workspace/folder situations)

CHANGELOG.md, src/calva-fmt/src/format.ts
When formatting current form, we actually mean current enclosing form. This breaks down on top level forms. The old way of finding the enclosing form handled this, but it was lost in translation when changing the method. This PR fixes that by this logic:
> If finding the current enclosing form fails -> use the current form.
In addition to this I've made the command format the whole document when issued in the void between top level forms.
Fixes #640 
I have:
=> Special treatment for formatting top-level forms

CHANGELOG.md, src/connector.ts, src/debugger/calva-debug.ts, src/debugger/decorations.ts, src/extension.ts, src/nrepl/index.ts, src/providers/annotations.ts
- Refactor debugger code
- Clear annotations in all visible editors when debugger quits
- Fixes #647 
I have:
=> Refactor debugger code

CHANGELOG.md, package-lock.json, src/evaluate.ts
- Send output messages to calva says window as they're received from nrepl, instead of all at once when the whole evaluation is completed. This matches the functionality of the repl window.
@PEZ Just fyi, this also removes the `stdout:` prefix to stdout messages - I think this looks cleaner, especially since with this change messages are streamed as received (the `stdout:` prefix would clutter the output). This matches the repl window as well. I think it makes sense to still label errors as such - but stdout can just be without label and understood as such.
As an example:
```clojure
(do
(println "First")
(Thread/sleep 1000)
(println "Second")
(Thread/sleep 1000)
(println "Third")
(/ 1 0))
```
The above code would not show any of the println outputs in the Calva says window, just the …
=> WIP - Stream output messages to Calva Says as they're received

CHANGELOG.md, src/debugger/calva-debug.ts, src/evaluate.ts, src/nrepl/index.ts
- Add analytics to debugger to gauge usage
I have:
=> Add analytics to debugger

CHANGELOG.md, src/evaluate.ts, src/testRunner.ts, src/utilities.ts
- TestOnSave: Check that the file saved is not the output window before loading file and running tests
- Move test output to output window
- Make `loadFile` update output window session properly
Fixes #712
I have:
=> Fix tests starting an infinite evaluate file loop when output window is saved

CHANGELOG.md, src/evaluate.ts, src/result-output.ts
- Check if the the current `ns` of the repl is different from what the form to be evaluated should be using before evaluating `(in-ns ...)`.
- Add pre-eval (conditional) to the commands for setting the output window ns and copying over forms to the repl window.
Fixes #724
I have:
=> Fix dynamic eval vars in output/repl window

CHANGELOG.md, README.md, src/extension.ts, src/providers/definition.ts, src/results-output/results-doc.ts
- Use 0 for column of symbol if not returned from :info nrepl op
Fixes #636 
I have:
=> Fix go to definition for namespaces

CHANGELOG.md, src/results-output/results-doc.ts
- Adds validation for the existence of an activeTextEditor
Fixes #734
I have:
=> Adds validation for the existence of an activeTextEditor

CHANGELOG.md, package.json, src/config.ts, src/providers/annotations.ts
- Change output file extension to .calva-repl
Resolves #754 
I have:
=> Change output file extension

CHANGELOG.md, package-lock.json, src/liveShareSupport.ts
- Check for shared port existence before calling `dispose` on it
Fixes #856 
I have:
=> Fix live share jackout error

docs/site/reveal.md, mkdocs.yml
- Adds page to document how to use Reveal with Calva.
I have:
=> Adds page about using Reveal with Calva

CHANGELOG.md, package-lock.json
- Fixes corrupt package-lock.json
Fixes #866 
I have:
=> Generate new package-lock.json

CHANGELOG.md, docs/site/custom-commands.md, src/evaluate.ts
This is the same as #874 .
I just added update of changelog and white space.
In #874 I picked the wrong branch.
I propose to merge this one, and then close both.
=> implemented substitutions in custom commands - PR 2

src/lsp.ts, src/providers/hover.ts
Also use lsp hovers and completions when not connected
Ping  @bpringe
=> Remove hover info about connecting to REPL

CHANGELOG.md, docs/site/customizing.md, docs/site/jack-in-guide.md, package.json, src/nrepl/project-types.ts, src/state.ts
We make the jack-in deps configurable and also bump them all to latest versions with the provided default settings.
Fixes #896
Closes #852 
I have:
=> Make jack-in deps versions configurable

CHANGELOG.md, docs/site/output.md, package.json, src/evaluate.ts, src/extension.ts, src/results-output/results-doc.ts, src/state.ts, src/utilities.ts
Add command opening current repl window ns file
Fixes #920
I have:
=> 920 switch to editor for ns

CHANGELOG.md, docs/site/customizing.md, package.json
=> Bump cider-nrepl to 0.25.6

CHANGELOG.md, src/calva-fmt/src/extension.ts
Fixes #884
I have:
- [ x Smoke tested the extension as such.
=> Add single quote to language definition word pattern

CHANGELOG.md, src/cursor-doc/paredit.ts, src/doc-mirror/index.ts, src/extension-test/unit/cursor-doc/paredit-test.ts
We now add a space to separate the slurped form from the last form in the slurping list. If necessary. We also always trim surrounding whitespace after paredit operations.
Fixes #883
I have:
=> 883 slurp forward ws

CHANGELOG.md, download-lsp.js
- Add clojure-lsp version to download script so that we can correlate the lsp version to Calva version
Closes #913 
I have:
=> Improve clojure lsp integration 2
